name: "Update Config to S3"

on:
  push:
    branches: ["main"]
  # Skipped by commits by add remove service workflows
  # as they include skip ci in the commit message
  # and call directly instead
  #
  # We will be able to restrict the paths if we can work out how Portal can get the latest version of s3 pushed commits
  #    paths:
  #      - "global/**"
  #      - "environments/**"
  #      - "services/**"

  workflow_call:
    inputs:
      commit-ref:
        description: The commit ref to sync
        type: string
        required: true
  workflow_dispatch:
    inputs:
      commit-ref:
        description: The commit ref to sync, empty means HEAD
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: read
  id-token: write

jobs:
  commit-hash:
    name: "Commit hash"
    runs-on: ubuntu-latest
    outputs:
      commit-ref: ${{ steps.commit-hash.outputs.commit-ref }}
    steps:
      - name: Get commit hash
        id: commit-hash
        run: |
          echo commit ref 1 is ${{ inputs.commit-ref }}
          echo commit ref 2 is ${{ github.event.inputs.commit-ref }}
          if [ -z "${{ github.event.inputs.commit-ref }}" ]; then
            echo "commit-ref=${{ github.sha }}" >> $GITHUB_OUTPUT
          else
            echo "commit-ref=${{ github.event.inputs.commit-ref }}" >> $GITHUB_OUTPUT
          fi

  update_config_environment:
    strategy:
      matrix:
        environment:
          - id: infra-dev
            aws_account_id: "123"
          - id: management
            aws_account_id: "123213"

    name: "Environment: ${{ matrix.environment.id }}"
    needs: commit-hash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.commit-hash.outputs.commit-ref }}
      - name: Configure AWS credentials
        run: echo Hello ${{ matrix.environment.id }} ${{ matrix.environment.aws_account_id }}
