name: Validate config

on:
  workflow_call
  #  inputs:
  #    branchName:
  #      description: "Branch name"
  #      required: true
  #      type: string

jobs:
  validate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validating config
        run: |
          echo "Validating configurations"
