name: Merge config

on:
  workflow_call:
    inputs:
      repositoryName:
        description: "Repository name"
        required: true
        type: string

jobs:
  merge-commit-branch:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Checkout branch
        run: |
          git config --global user.email "30552+flurdy@users.noreply.github.com"
          git config --global user.name "flurdy"
          git checkout create-config-${{ inputs.repositoryName }}
          git pull
          git checkout main
          git pull
      - name: Merge to main
        run: |
          git merge --no-ff --no-commit create-config-${{ inputs.repositoryName }}
      - name: Push merge
        run: |
          git push origin main
