name: Create config commit

on:
  workflow_call:
    inputs:
      repositoryName:
        description: "Repository name"
        required: true
        type: string

jobs:
  create-commit-and-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Commit a change
        run: |
          git config --global user.email "30552+flurdy@users.noreply.github.com"
          git config --global user.name "flurdy"
          git checkout -b create-config-${{ inputs.repositoryName }}
          mkdir -p services/${{ inputs.repositoryName }}/dev
          echo "New commit" >> services/${{ inputs.repositoryName }}/defaults.env
          echo "New commit" >> services/${{ inputs.repositoryName }}/dev/${{ inputs.repositoryName }}.env
          git add services/${{ inputs.repositoryName }}
          git commit -m "Add service ${{ inputs.repositoryName }}"
          git push origin create-config-${{ inputs.repositoryName }}
