name: Create config commit

on:
  workflow_call:
    inputs:
      repositoryName:
        description: "Repository name"
        required: true
        type: string

jobs:
  create-commit-branch:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      service-root: services/${{ inputs.repositoryName }}
      service-branch: create-config-${{ inputs.repositoryName }}
    outputs:
      service-branch: ${{ env.service-branch }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Commit a change
        run: |
          git config --global user.email "30552+flurdy@users.noreply.github.com"
          git config --global user.name "flurdy"
          git checkout -b ${{ env.service-branch }}
          mkdir -p ${{ env.service-root }}/dev
          echo "New commit" >> ${{ env.service-root}}/defaults.env
          echo "New commit" >> ${{ env.service-root}}/dev/${{ inputs.repositoryName }}.env
          git add ${{ env.service-root }}
          git commit -m "Add service ${{ inputs.repositoryName }}"
      - name: Push change
        run: |
          git push -u origin ${{ env.service-branch }}

  validate-commit:
    uses: ./.github/workflows/commit-validation.yml
    needs: create-commit-branch
    permissions:
      contents: read
