name: Create config commit

on:
  workflow_call:
    inputs:
      repositoryName:
        description: "Repository name"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      repositoryName:
        description: "Repository name"
        required: true
        type: string

env:
  service-branch: create-config-${{ inputs.repositoryName }}

jobs:
  validate-service:
    uses: ./.github/workflows/service-validation.yml
    with:
      repositoryName: ${{ inputs.repositoryName }}

  create-commit-branch:
    needs: validate-service
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      service-root: services/${{ inputs.repositoryName }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Commit a change
        run: |
          git config --global user.email "30552+flurdy@users.noreply.github.com"
          git config --global user.name "flurdy"
          git checkout -b ${{ env.service-branch }}
          mkdir -p ${{ env.service-root }}/dev
          echo "New commit" >> ${{ env.service-root}}/defaults.env
          echo "New commit" >> ${{ env.service-root}}/dev/${{ inputs.repositoryName }}.env
          git add ${{ env.service-root }}
          git commit -m "Add service ${{ inputs.repositoryName }}"
      - name: Push change
        run: |
          git push -u origin ${{ env.service-branch }}

  validate-commit:
    uses: ./.github/workflows/commit-validation.yml
    needs: create-commit-branch
    permissions:
      contents: read
    with:
      branchName: ${{ env.service-branch }}

  merge-commit-branch:
    needs: validate-commit
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Fetch branches
        run: |
          git fetch
      - name: Checkout branch
        run: |
          git config --global user.email "30552+flurdy@users.noreply.github.com"
          git config --global user.name "flurdy"
          git checkout ${{ env.service-branch }}
          git checkout main
      - name: Merge to main
        run: |
          git merge --no-ff ${{ env.service-branch }}
      - name: Push merge
        run: |
          git push origin main
      - name: Delete branch
        run: |
          git branch -d ${{ env.service-branch }}
          git push origin -d ${{ env.service-branch }}
