name: Create config commit

on:
  workflow_call:
    inputs:
      repositoryName:
        description: "Repository name"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      repositoryName:
        description: "Repository name"
        required: true
        type: string

env:
  service-branch: create-config-${{ inputs.repositoryName }}

jobs:
  validate-service:
    uses: ./.github/workflows/service-validation.yml
    with:
      repositoryName: ${{ inputs.repositoryName }}

  create-commit-branch:
    needs: validate-service
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      service-root: services/${{ inputs.repositoryName }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Commit a change
        run: |
          git config --global user.email "30552+flurdy@users.noreply.github.com"
          git config --global user.name "flurdy"
          git checkout -b ${{ env.service-branch }}
          mkdir -p ${{ env.service-root }}/dev
          echo "New commit" >> ${{ env.service-root}}/defaults.env
          echo "New commit" >> ${{ env.service-root}}/dev/${{ inputs.repositoryName }}.env
          git add ${{ env.service-root }}
          git commit -m "Add service ${{ inputs.repositoryName }}"
      - name: Push change
        run: |
          git push -u origin ${{ env.service-branch }}
      - name: List branches
        run: |
          echo "Branches"
          git branch -a
          echo "Remote branches"
          git branch -r
      # - name: Merge to main
      #   run: |
      #     git merge --no-ff --no-commit ${{ env.service-branch }}
      # - uses: actions/upload-artifact@v4
      #   name: "Temporary upload git repo"
      #   with:
      #     name: gitrepo-v4
      #     path: .

  validate-commit:
    uses: ./.github/workflows/commit-validation.yml
    needs: create-commit-branch
    permissions:
      contents: read

  merge-commit-branch:
    needs: validate-commit
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # - name: Remove git
      #   run: |
      #     rm -rf .git
      # - uses: actions/download-artifact@v4
      #   name: "Download git repo"
      #   with:
      #     name: gitrepo-v4
      #     path: .
      - name: List branches
        run: |
          echo "Branches"
          git branch -a
          echo "Remote branches"
          git branch -r
      - name: Checkout branch
        run: |
          git config --global user.email "30552+flurdy@users.noreply.github.com"
          git config --global user.name "flurdy"
          git checkout ${{ env.service-branch }}
          git pull
          git checkout main
          git pull
      - name: Merge to main
        run: |
          git merge --no-ff --no-commit ${{ env.service-branch }}
      - name: Push merge
        run: |
          git push origin main
