name: Create config commit directly

on:
  workflow_dispatch:
    inputs:
      repositoryName:
        description: "Repository name"
        required: true
        type: string

env:
  service-branch: create-config-${{ inputs.repositoryName }}

jobs:
  validate-service:
    uses: ./.github/workflows/service-validation.yml
    with:
      repositoryName: ${{ inputs.repositoryName }}

  create-commit-branch:
    needs: validate-service
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    env:
      service-root: services/${{ inputs.repositoryName }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Commit a change
        run: |
          git config --global user.email "30552+flurdy@users.noreply.github.com"
          git config --global user.name "flurdy"
          mkdir -p ${{ env.service-root }}/dev
          echo "New commit" >> ${{ env.service-root}}/defaults.env
          echo "New commit" >> ${{ env.service-root}}/dev/${{ inputs.repositoryName }}.env
          git add ${{ env.service-root }}
          git commit -m "Add service ${{ inputs.repositoryName }}"

  validate-commit:
    uses: ./.github/workflows/commit-validation.yml
    needs: create-commit-branch
    permissions:
      contents: read

  merge-commit-branch:
    needs: validate-commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Fetch branches
        run: |
          git fetch
      - name: Push merge
        run: |
          git push origin main
