name: Merge config

on:
  workflow_call:
    inputs:
      repositoryName:
        description: "Repository name"
        required: true
        type: string

jobs:
  create-commit-and-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Merge to main
        run: |
          git checkout create-config-${{ inputs.repositoryName }}
          git pull
          git checkout main
          git pull
          git merge create-config-${{ inputs.repositoryName }}
          git push origin main
