name: Create config commit

on:
  workflow_call:
    inputs:
      repositoryName:
        description: "Repository name"
        required: true
        type: string

jobs:
  create-commit-and-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Commit a change
        run: |
          git config --global user.email "30552+flurdy@users.noreply.github.com"
          git config --global user.name "flurdy"
          git checkout -b create-config-${{ env.repositoryName }}
          mkdir -p services/${{ env.repositoryName }}/dev
          echo "New commit" >> services/${{ env.repositoryName }}/defaults.env
          echo "New commit" >> services/${{ env.repositoryName }}/dev/${{ env.repositoryName }}.env
          git add services/${{ env.repositoryName }}
          git commit -m "Add service ${{ env.repositoryName }}"
          git push origin create-config-${{ env.repositoryName }}
