name: Create config orchestration

on:
  workflow_dispatch:
    inputs:
      repositoryName:
        description: "Repository name"
        required: true
        type: string

jobs:
  validate-service:
    uses: ./.github/workflows/service-validation.yml
    with:
      repositoryName: ${{ env.repositoryName }}
    #  secrets:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-commit:
    uses: ./.github/workflows/config-commit.yml
    needs: validate-service
    with:
      repositoryName: ${{ env.repositoryName }}
    permissions:
      contents: write
    #  secrets:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  validate-commit:
    uses: ./.github/workflows/commit-validation.yml
    needs: create-commit
    permissions:
      contents: read

  merge-commit:
    uses: ./.github/workflows/config-merge.yml
    needs: validate-commit
    with:
      repositoryName: ${{ env.repositoryName }}
    permissions:
      contents: write
    #  secrets:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
