name: Create Commit and PR

on:
  workflow_dispatch:
    inputs:
      repositoryName:
        description: "Repository name"
        required: true
        type: string
  workflow_call:
    inputs:
      repositoryName:
        description: "Repository name"
        required: true
        type: string

jobs:
  create-commit-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref }}
      - name: Commit a change
        run: |
          git config --global user.email "30552+flurdy@users.noreply.github.com"
          git config --global user.name "flurdy"
          #  git checkout -b new-service-${{ env.repositoryName }}
          mkdir -p services/${{ env.repositoryName }}/dev
          echo "New commit" >> services/${{ env.repositoryName }}/defaults.env
          echo "New commit" >> services/${{ env.repositoryName }}/dev/${{ env.repositoryName }}.env
          git add services/${{ env.repositoryName }}
          git commit -m "Add service ${{ env.repositoryName }}"
          git push origin new-service-${{ env.repositoryName }}
          git checkout main
          git pull
          git merge new-service-${{ env.repositoryName }}
          git push
