name: Remove service configuration

on:
  workflow_call:
    inputs:
      repositoryName:
        description: "Repository name"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      repositoryName:
        description: "Repository name"
        required: true
        type: string

run-name: ${{ inputs.repositoryName }}

concurrency:
  group: ${{ github.workflow }}-${{ inputs.repositoryName }}
  cancel-in-progress: false

env:
  service-branch: remove-config-${{ inputs.repositoryName }}-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
  service-root: "services/${{ inputs.repositoryName }}"
  cdp-environments: "infra-dev management dev test perf-test prod"
  #   cdp-gitbot-email: "131385681+cdp-gh-bot[bot]@users.noreply.github.com"
  #   cdp-gitbot-name: "cdp-gh-bot[bot]"
  cdp-gitbot-email: "30552+flurdy@users.noreply.github.com"
  cdp-gitbot-name: "flurdy"

jobs:
  add_service:
    name: "Remove a service"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Checkout new branch
        run: git checkout -b ${{ env.service-branch }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # - name: Check config pre removal
      #   run: python validate.py
      - name: Configure git committer
        run: |
          git config user.email "${{ env.cdp-gitbot-email }}"
          git config user.name "${{ env.cdp-gitbot-name }}"
      - name: Remove service files
        run: |
          git rm ${{ env.service-root }}/defaults.env
          for cdpenv in ${{ env.cdp-environments }}; do
            git rm ${{ env.service-root }}/${cdpenv}/${{ inputs.repositoryName }}.env
          done
      # - name: Check config post removal
      #   run: python validate.py
      - name: Commit changes
        run: |
          git commit -m "Remove service configuration for ${{ inputs.repositoryName }}"
      - name: Push branch
        run: git push -u origin ${{ env.service-branch }}
      - name: Merge to main
        run: |
          git checkout main
          git merge --no-ff ${{ env.service-branch }}
      - name: Push merge
        run: git push origin main
      - name: Delete branch
        run: |
          git branch -d ${{ env.service-branch }}
          git push origin -d ${{ env.service-branch }}
