name: Service validation

on:
  workflow_call:
    inputs:
      repositoryName:
        description: "Repository name"
        required: true
        type: string

jobs:
  validate-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validating service
        run: |
          echo "Validating service ${{ inputs.repositoryName }} is a valid repository"
          if [ -n "${{ inputs.repositoryName }}" ]; then
            echo "Service ${{ inputs.repositoryName }} is a valid repository"
          else
            echo "Service ${{ inputs.repositoryName }} is not a valid repository"
            exit 1
          fi
